# shellcheck shell=bash
# shellcheck source=/dev/null
# https://github.com/nekwebdev/chocodots-lotus
# @nekwebdev
# LICENSE: GPLv3
#
# ~/.config/shell/bashrc
#
# symlink to ~/.bashrc
# every interactive non-login shell reads .bashrc first.
# sources our aliases and is the place to add bash related functions.
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

[[ -f "$XDG_CONFIG_HOME/shell/aliasrc" ]] && source "$XDG_CONFIG_HOME/shell/aliasrc"

PS1='[\u@\h \W]\$ '

if [[ -f "$HOME/.local/src/dotbare/dotbare.plugin.bash" ]]; then
  source "$HOME/.local/src/dotbare/dotbare.plugin.bash"
  _dotbare_completion_cmd dots
fi