# shellcheck shell=bash
# shellcheck source=/dev/null
# https://github.com/nekwebdev/chocodots-lotus
# @nekwebdev
# LICENSE: GPLv3
#
# ~/.config/shell/bashrc
#
# symlink to ~/.bashrc
# every interactive non-login shell reads .bashrc first.
# sources our aliases and is the place to add bash related functions.
#
# sources: ChrisTitusTech

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# sourced from zachbrowne.me

# Source global definitions
if [ -f /etc/bashrc ]; then
	 . /etc/bashrc
fi

# check the window size after each command and, if necessary, update the values of LINES and COLUMNS
shopt -s checkwinsize

# causes bash to append to history instead of overwriting it so if you start a new terminal, you have old session history
shopt -s histappend
PROMPT_COMMAND='history -a'

# only if running interactively
if [[ $- == *i* ]]; then
  # allow ctrl-S for history navigation (with ctrl-R)
	stty -ixon
  # better bash auto complete
  bind '"\t": menu-complete'
  bind '"\e[Z": menu-complete-backward'
  bind '"\e[A": history-search-backward'
  bind '"\e[B": history-search-forward'
  bind '"\eOA": history-search-backward'
  bind '"\eOB": history-search-forward'
fi

# color for manpages in less makes manpages a little easier to read
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# source aliases
[[ -f "$XDG_CONFIG_HOME/shell/aliasrc" ]] && source "$XDG_CONFIG_HOME/shell/aliasrc"

# source completions
if [[ -f "$HOME/.local/src/dotbare/dotbare.plugin.bash" ]]; then
  source "$HOME/.local/src/dotbare/dotbare.plugin.bash"
  _dotbare_completion_cmd dots
fi

# Enable bash programmable completion features in interactive shells
if [ -f /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi

# custom prompt
eval "$(starship init bash)"

# zoxide, better cd
eval "$(zoxide init bash)"
