# shellcheck shell=bash
# https://github.com/nekwebdev/chocodots-lotus
# @nekwebdev
# LICENSE: GPLv3
#
# ~/.config/shell/bash_logout
#
# symlink to ~/.bash_logout
# commands to excecute before logging out.
#

# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi